// Generated by tools/build-qml.py from tokens/palette.json. Do not edit.
pragma Singleton
import QtQuick

/**
 * Kante palette for apps: the roles KanteStyle reads, for the dark theme
 * and the light theme "Leinen". Surfaces carry alpha (#aarrggbb) so a
 * translucent or blurred platform ground shows through.
 */
QtObject {
    readonly property string version: "1.2.0"

    readonly property QtObject dark: QtObject {
        readonly property color text: "#ebdbb2"
        readonly property color strongText: "#fbf1c7"
        readonly property color mutedText: "#bdae93"
        readonly property color disabledText: "#a89984"
        readonly property color ground: "#1d2021"
        readonly property color accent: "#fabd2f"
        readonly property color accentText: "#fabd2f"
        readonly property color accentForeground: "#1d2021"
        readonly property color positive: "#8ec07c"
        readonly property color neutral: "#fe8019"
        readonly property color negative: "#fb4934"
        readonly property color info: "#83a598"
        readonly property color card: "#993c3836"
        readonly property color sunken: "#80141312"
        readonly property color frame: "#29ebdbb2"
        readonly property color rule: "#24ebdbb2"
        readonly property color dialog: "#f7282828"
    }

    readonly property QtObject light: QtObject {
        readonly property color text: "#3c3836"
        readonly property color strongText: "#282828"
        readonly property color mutedText: "#665c54"
        readonly property color disabledText: "#6a5f52"
        readonly property color ground: "#f0e9d6"
        readonly property color accent: "#d79921"
        readonly property color accentText: "#8a5a00"
        readonly property color accentForeground: "#282828"
        readonly property color positive: "#427b58"
        readonly property color neutral: "#af3a03"
        readonly property color negative: "#9d0006"
        readonly property color info: "#076678"
        readonly property color card: "#b2fbf8ee"
        readonly property color sunken: "#99e6dec6"
        readonly property color frame: "#2e3c3836"
        readonly property color rule: "#243c3836"
        readonly property color dialog: "#faf7f2e4"
    }

    // Brand mark fill (icon, badges); not for controls.
    readonly property color brand: "#e8dcc4"

    // Shape (px at a grid unit of 18; KanteStyle scales them).
    readonly property int chamfer: 16
    readonly property int chamferSmall: 10

    // Type
    readonly property string headingFamily: "Rajdhani"
    readonly property real headingLetterSpacing: 0.08
    readonly property real labelLetterSpacing: 0.14
}
