#!/usr/bin/env python3
"""Generates Knust's palette from Kante's tokens.

  docs/v1/knust-palette.css   -> https://shrippen.github.io/v1/knust-palette.css

Knust (shrippen/kimai-knust-bundle, the Kimai theme) vendors this file unchanged
(bin/sync-palette.sh there) and maps it onto Tabler by hand. Names are Knust's:
--shr-<token>, with --shr-void / --shr-hard / --shr-panel for bg-void / bg-hard /
bg-panel, and every colour also as --shr-<name>-rgb ("r, g, b") because Bootstrap
utilities need rgba(var(--tblr-x-rgb), a).

  palette.json  ──► hex values per theme (dark = Gruvbox, light = Leinen), scrim,
                    primary, on-state, the grey scale (palette.json "knust")
  variables.css ──► role, tint, data and map expressions (:root block), renamed

Usage: python3 kante/tools/build-knust.py   (build.sh runs it)
"""
import json
import re
from pathlib import Path

KANTE = Path(__file__).resolve().parent.parent
REPO = KANTE.parent
OUT = REPO / "docs/v1/knust-palette.css"
PALETTE = json.loads((KANTE / "tokens/palette.json").read_text())
VARIABLES = (KANTE / "tokens/variables.css").read_text()

# Kante token -> Knust name (everything else keeps its name)
RENAME = {"bg-void": "void", "bg-hard": "hard", "bg-panel": "panel"}

# Roles that follow the theme through var(); taken from variables.css as they are
ROLES = ["hl", "focus", "link", "info", "warn", "danger", "score",
         "map-marker", "map-route", "entity-fallback",
         "tint-1", "tint-2", "tint-hl", "tint-hl-2", "tint-warn",
         "d1", "d2", "d3", "d4", "d5", "d6"]

VAR = re.compile(r"var\(--([\w-]+)\)")

HEADER = """/*
 * Knust palette — generated by kante/tools/build-knust.py from kante/tokens/palette.json
 * and kante/tokens/variables.css. Do not edit; Knust vendors it unchanged
 * (bin/sync-palette.sh). Kante {version}: https://github.com/shrippen/shrippen.github.io
 *
 *   :root, [data-bs-theme=light]   Leinen
 *   [data-bs-theme=dark]           Gruvbox dark
 *   :root, [data-bs-theme]         roles, tints, data palette, map roles, grey scale
 */
"""


def knust(name):
    return RENAME.get(name, name)


def theme_colours(theme):
    """Ordered (Kante name, hex) of one theme."""
    dark = []
    dark += PALETTE["backgrounds"].items()
    dark += PALETTE["foregrounds"].items()
    dark += [(n, v["bright"]) for n, v in PALETTE["semantic"].items()]
    dark += [(n + "-n", v["neutral"]) for n, v in PALETTE["semantic"].items()]
    dark += PALETTE["extra"].items()
    tokens = dict(dark)
    app = PALETTE["app"]["dark"]
    dark += [("primary", tokens["yellow"]), ("on-primary", tokens["bg-void"]),
             ("on-state", tokens[app["onState"]])]
    if theme == "dark":
        return dark

    # Leinen: its own steps and inks; the quiet neutrals (-n) are the dark ones
    light = PALETTE["light"]
    values = dict(dark)
    values.update(light["backgrounds"])
    values.update(light["foregrounds"])
    values.update({n: v for n, v in light["semantic"].items() if not n.endswith("-hover")})
    extra = light["extra"]
    values.update({k: extra[k] for k in ("cyan-tint", "yellow-hi", "yellow-lo", "primary", "on-primary", "on-state")})
    return [(n, values[n]) for n, _ in dark]


def scrim(theme):
    """(colour, opacity) behind dialogs: Tabler takes them separately."""
    ref, alpha = PALETTE["app"][theme]["scrim"]
    return dict(theme_colours(theme))[ref], alpha


def rgb(hexv):
    h = hexv.lstrip("#")
    return ", ".join(str(int(h[i:i + 2], 16)) for i in (0, 2, 4))


def theme_block(theme):
    lines = []
    for name, value in theme_colours(theme):
        lines.append(f"    --shr-{knust(name)}: {value.lower()};")
        lines.append(f"    --shr-{knust(name)}-rgb: {rgb(value)};")
    colour, alpha = scrim(theme)
    lines.append(f"    --shr-scrim-bg: {colour.lower()};")
    lines.append(f"    --shr-scrim-opacity: {alpha};")
    return "\n".join(lines)


def root_props():
    """Custom properties of variables.css's :root block (dark, the role definitions)."""
    start = VARIABLES.index(":root {")
    body = VARIABLES[start:VARIABLES.index("\n}", start)]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    return {m.group(1): " ".join(m.group(2).split()) for m in re.finditer(r"--([\w-]+)\s*:\s*([^;]+);", body)}


def roles_block():
    props = root_props()
    rename = lambda m: f"var(--shr-{knust(m.group(1))})"
    lines = [f"    --shr-{r}: {VAR.sub(rename, props[r])};" for r in ROLES]
    for step, ref in PALETTE["knust"]["gray"].items():
        if ref.startswith("#"):
            value = ref
        else:
            theme, token = ref.split(".", 1)
            value = dict(theme_colours(theme))[token]
        lines.append(f"    --shr-gray-{step}: {value.lower()};")
    return "\n".join(lines)


css = (HEADER.format(version=PALETTE["meta"]["version"])
       + "\n:root,\n[data-bs-theme=light] {\n" + theme_block("light") + "\n}\n"
       + "\n[data-bs-theme=dark] {\n" + theme_block("dark") + "\n}\n"
       + "\n:root,\n[data-bs-theme] {\n" + roles_block() + "\n}\n")
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(css)
print(f"built {OUT.relative_to(REPO)} ({len(css)} bytes)")
