#!/usr/bin/env python3
"""Generates the QML side of Kante from tokens/palette.json.

  qml/Kante/qmldir             every Kante*.qml component
  qml/Kante/KantePalette.qml   app roles for dark and light ("Leinen"), resolved
                               from the palette (singleton used by KanteStyle)
  qml/KantePlasma/KantePlasmaButton.qml   the Plasma widget button, generated from
                               qml/Kante/KanteButton.qml (PlasmaComponents3 base)
  tokens/palette.qml           flat brand palette for Plasma widgets (reference)
  qml/Kante/fonts/             the bundled fonts from fonts/ plus OFL.txt

Both .qml files are generated: edit tokens/palette.json and run ./build.sh.
Usage: python3 kante/tools/build-qml.py   (paths below are relative to kante/)
"""
import json
import shutil
from pathlib import Path

KANTE = Path(__file__).resolve().parent.parent
PALETTE = json.loads((KANTE / "tokens/palette.json").read_text())
MODULE = KANTE / "qml/Kante"
HEADER = "// Generated by kante/tools/build-qml.py from kante/tokens/palette.json. Do not edit."


def theme_tokens(theme):
    """Token name -> hex for one theme ("dark" or "light")."""
    if theme == "dark":
        t = dict(PALETTE["backgrounds"])
        t.update(PALETTE["foregrounds"])
        t.update({name: v["bright"] for name, v in PALETTE["semantic"].items()})
        t["accent-brand"] = PALETTE["accent"]
        t.update(PALETTE.get("extra", {}))
        return t
    light = PALETTE["light"]
    t = dict(theme_tokens("dark"))
    t.update(light["backgrounds"])
    t.update(light["foregrounds"])
    t.update(light["semantic"])
    t["accent-brand"] = light["accent"]
    t.update(light.get("extra", {}))
    return t


def resolve(value, tokens):
    """A role value: token name, "#rrggbb", or [token, alpha] -> QML colour string."""
    alpha = None
    if isinstance(value, list):
        value, alpha = value
    hexv = value if value.startswith("#") else tokens[value]
    hexv = hexv.lower()
    if alpha is None:
        return hexv
    return "#%02x%s" % (round(alpha * 255), hexv[1:])


def camel(name):
    head, *rest = name.split("-")
    return head + "".join(p.capitalize() for p in rest)


def roles_block(theme):
    tokens = theme_tokens(theme)
    lines = []
    for role, value in PALETTE["app"][theme].items():
        lines.append(f'        readonly property color {role}: "{resolve(value, tokens)}"')
    return "\n".join(lines)


def write_palette_module():
    shape = PALETTE["shape"]
    typo = PALETTE["typography"]
    text = f"""{HEADER}
pragma Singleton
import QtQuick

/**
 * Kante palette for apps: the roles KanteStyle reads, for the dark theme
 * and the light theme "Leinen". Surfaces carry alpha (#aarrggbb) so a
 * translucent or blurred platform ground shows through.
 */
QtObject {{
    readonly property string version: "{PALETTE['meta']['version']}"

    readonly property QtObject dark: QtObject {{
{roles_block('dark')}
    }}

    readonly property QtObject light: QtObject {{
{roles_block('light')}
    }}

    // Brand mark fill (icon, badges); not for controls.
    readonly property color brand: "{PALETTE['accent']}"

    // Shape (px at a grid unit of 18; KanteStyle scales them).
    readonly property int chamfer: {shape['chamfer']}
    readonly property int chamferSmall: {shape['chamferSmall']}
    readonly property int cutSmall: {shape['cutSmall']}
    // Control heights (small, medium, large).
    readonly property int heightSmall: {shape['heights']['small']}
    readonly property int heightMedium: {shape['heights']['medium']}
    readonly property int heightLarge: {shape['heights']['large']}

    // Type
    readonly property string headingFamily: "{typo['heading']}"
    readonly property real headingLetterSpacing: {typo['headingLetterSpacing']}
    readonly property real labelLetterSpacing: {typo['labelLetterSpacing']}
}}
"""
    (MODULE / "KantePalette.qml").write_text(text)


def write_flat_palette():
    lines = [HEADER, "pragma Singleton", "import QtQuick", "",
             "/*",
             " * Kante — flat palette reference for Plasma widgets and other QML.",
             " * https://github.com/shrippen/shrippen.github.io",
             " *",
             " * Widgets that follow the Plasma theme use Kirigami.Theme.* for all",
             " * interactive colors and these only for brand elements (icon fills,",
             " * priority bands, project hashes, version badges). The opt-in Kante",
             " * style for apps lives in qml/Kante (KanteStyle).",
             " */",
             "QtObject {",
             f'    readonly property color accent: "{PALETTE["accent"]}"', ""]
    for group in ("backgrounds", "foregrounds"):
        for name, value in PALETTE[group].items():
            lines.append(f'    readonly property color {camel(name)}: "{value}"')
        lines.append("")
    for name, v in PALETTE["semantic"].items():
        lines.append(f'    readonly property color {name}: "{v["bright"]}"')
    lines.append("")
    for name, v in PALETTE["semantic"].items():
        lines.append(f'    readonly property color {name}N: "{v["neutral"]}"')
    lines.append("}")
    (KANTE / "tokens/palette.qml").write_text("\n".join(lines) + "\n")


def write_plasma_button():
    """KantePlasmaButton is KanteButton on PlasmaComponents3: generated, so they never drift."""
    src = (MODULE / "KanteButton.qml").read_text()
    text = src.replace("import QtQuick.Controls as QQC2\n", "")
    text = text.replace('import "."\n', 'import org.kde.plasma.components as PlasmaComponents3\nimport "../Kante"\n')
    text = text.replace("QQC2.", "PlasmaComponents3.").replace("KanteButton", "KantePlasmaButton")
    text = text.replace(" * Push button.\n *   System  a plain button of the active style (unchanged).",
                        " * Push button of a Plasma widget (PlasmaComponents3).\n *   System  a plain Plasma button (unchanged).")
    text = text.replace(" * In Kante the style's frame and content stay (they size the button) but are\n * hidden; frame, icon and text are drawn here.",
                        " * In Kante the Plasma frame and content stay (they size the button) but are\n * hidden; frame, icon and text are drawn here, so disabled buttons fade\n * instead of taking the Plasma theme's disabled colors.")
    text = "// Generated by kante/tools/build-qml.py from qml/Kante/KanteButton.qml. Do not edit.\n" + text
    (KANTE / "qml/KantePlasma/KantePlasmaButton.qml").write_text(text)


def write_qmldir():
    """qml/Kante/qmldir lists every Kante*.qml; the two singletons first."""
    lines = ["module Kante", "singleton KanteStyle 1.0 KanteStyle.qml", "singleton KantePalette 1.0 KantePalette.qml"]
    for f in sorted(MODULE.glob("Kante*.qml")):
        if f.stem not in ("KanteStyle", "KantePalette"):
            lines.append(f"{f.stem} 1.0 {f.name}")
    (MODULE / "qmldir").write_text("\n".join(lines) + "\n")


def copy_fonts():
    dest = MODULE / "fonts"
    dest.mkdir(parents=True, exist_ok=True)
    for name in PALETTE["typography"]["bundled"] + ["OFL.txt"]:
        shutil.copy2(KANTE / "fonts" / name, dest / name)


MODULE.mkdir(parents=True, exist_ok=True)
write_palette_module()
write_flat_palette()
write_plasma_button()
write_qmldir()
copy_fonts()
print("built kante/qml/Kante/KantePalette.qml, kante/tokens/palette.qml, kante/qml/Kante/fonts/")
