// Generated by tools/build-qml.py from tokens/palette.json. Do not edit.
pragma Singleton
import QtQuick

/*
 * Kante — flat palette reference for Plasma widgets and other QML.
 * https://github.com/shrippen/shrippen.github.io
 *
 * Widgets that follow the Plasma theme use Kirigami.Theme.* for all
 * interactive colors and these only for brand elements (icon fills,
 * priority bands, project hashes, version badges). The opt-in Kante
 * style for apps lives in qml/Kante (KanteStyle).
 */
QtObject {
    readonly property color accent: "#e8dcc4"

    readonly property color bgVoid: "#141312"
    readonly property color bgHard: "#1d2021"
    readonly property color bg0: "#282828"
    readonly property color bg1: "#3c3836"
    readonly property color bg2: "#504945"
    readonly property color bgPanel: "#2a2826"

    readonly property color fg0: "#fbf1c7"
    readonly property color fg1: "#ebdbb2"
    readonly property color fg2: "#d5c4a1"
    readonly property color fg3: "#a89984"

    readonly property color blue: "#83a598"
    readonly property color aqua: "#8ec07c"
    readonly property color green: "#b8bb26"
    readonly property color yellow: "#fabd2f"
    readonly property color orange: "#fe8019"
    readonly property color red: "#fb4934"
    readonly property color purple: "#d3869b"

    readonly property color blueN: "#458588"
    readonly property color aquaN: "#689d6a"
    readonly property color greenN: "#98971a"
    readonly property color yellowN: "#d79921"
    readonly property color orangeN: "#d65d0e"
    readonly property color redN: "#cc241d"
    readonly property color purpleN: "#b16286"
}
