#!/usr/bin/env python3
"""Studio Weber, the shared demo world of all shrippen projects.

demo/world.json is the source. `python3 demo/world.py build` expands it into
demo/dist/world.json (plus world.js with the data embedded, for QML and Node,
and DemoWorld.php), which demo/tools/sync-demo.py copies into every project:
the week templates become one row per timesheet, so no project has to repeat
that logic. Every date in the built file is still a day offset from the anchor.

Runtime rules (the same in world.js and DemoWorld.php):
  today  = DEMO_TODAY (YYYY-MM-DD) if set, else the real date
  anchor = Monday of the week that contains today
  date   = anchor + offset days
  text   = value[lang] if value is a {de, en} dict, else value

This module also works as a library: `from world import World`.
"""
import datetime as dt
import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "world.json"
DIST = HERE / "dist" / "world.json"
LANGS = ("de", "en")


def today():
    raw = os.environ.get("DEMO_TODAY", "").strip()
    return dt.date.fromisoformat(raw) if raw else dt.date.today()


def anchor(day=None):
    day = day or today()
    return day - dt.timedelta(days=day.weekday())


def text(value, lang):
    if isinstance(value, dict) and set(value) <= set(LANGS) and value:
        return value.get(lang) or value.get("en") or ""
    return value


def _minutes(hhmm):
    h, m = hhmm.split(":")
    return int(h) * 60 + int(m)


def expand_timesheets(world):
    """One row per timesheet: {id, user, project, activity, day, start, end, description, exported}."""
    spec = world["timesheet_weeks"]
    absent = {}
    for a in world["absences"]:
        if a["status"] == "approved":
            for d in range(a["from"], a["to"] + 1):
                absent.setdefault(a["user"], set()).add(d)
    billable = {p["id"]: p["billable"] for p in world["projects"]}
    rows = []
    for user, templates in spec["templates"].items():
        for week in range(spec["from_week"], spec["to_week"] + 1):
            for weekday, project, activity, start, end, desc in templates[week % len(templates)]:
                day = week * 7 + weekday
                if day in absent.get(user, ()):
                    continue
                rows.append({
                    "user": user, "project": project, "activity": activity, "day": day,
                    "start": start, "end": end, "description": desc,
                    "exported": billable[project] and day < spec["exported_before_day"],
                })
    rows.sort(key=lambda r: (r["day"], _minutes(r["start"]), r["user"]))
    for i, r in enumerate(rows, 1):
        r["id"] = i
    return rows


def build():
    world = json.loads(SOURCE.read_text(encoding="utf-8"))
    ids = {kind: {x["id"] for x in world[kind]} for kind in ("people", "customers", "projects", "activities")}
    world["timesheets"] = expand_timesheets(world)
    for r in world["timesheets"] + world["running"]:
        assert r["user"] in ids["people"], r
        assert r["project"] in ids["projects"], r
        assert r["activity"] in ids["activities"], r
    for p in world["projects"]:
        assert p["customer"] in ids["customers"], p
    DIST.parent.mkdir(exist_ok=True)
    DIST.write_text(json.dumps(world, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    js = (HERE / "lib" / "world.js").read_text(encoding="utf-8")
    (DIST.parent / "world.js").write_text(
        "// Generated by demo/world.py from demo/world.json. Do not edit.\n"
        f"var WORLD_DATA = {json.dumps(world, ensure_ascii=False)};\n\n{js}", encoding="utf-8")
    (DIST.parent / "DemoWorld.php").write_text((HERE / "lib" / "DemoWorld.php").read_text(encoding="utf-8"), encoding="utf-8")
    return world


class World:
    """Built world with resolved dates and texts for one language."""

    def __init__(self, lang="de", path=DIST, day=None):
        self.data = json.loads(Path(path).read_text(encoding="utf-8"))
        self.lang = lang
        self.today = day or today()
        self.anchor = anchor(self.today)
        self.today_offset = (self.today - self.anchor).days

    def date(self, offset):
        return self.anchor + dt.timedelta(days=offset)

    def t(self, value):
        return text(value, self.lang)

    def by_id(self, kind):
        return {x["id"]: x for x in self.data[kind]}

    def past_timesheets(self, now=None):
        """Timesheets up to now, without the ones that would overlap a running timer."""
        now = now or dt.datetime.now().strftime("%H:%M")
        running = {r["user"]: r["start"] for r in self.data["running"]}
        out = []
        for r in self.data["timesheets"]:
            if r["day"] > self.today_offset:
                continue
            if r["day"] == self.today_offset:
                limit = running.get(r["user"], now)
                if _minutes(r["end"]) > _minutes(min(limit, now)):
                    continue
            out.append(r)
        return out


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "build"
    if cmd == "build":
        w = build()
        print(f"built {DIST.relative_to(HERE.parent)}: {len(w['timesheets'])} timesheets, "
              f"{len(w['tasks']['items'])} tasks, {len(w['receipts'])} receipts")
    elif cmd == "dates":
        w = World(sys.argv[2] if len(sys.argv) > 2 else "de")
        print(f"today {w.today} (offset {w.today_offset}), anchor {w.anchor}")
    else:
        sys.exit(__doc__)
