#!/usr/bin/env bash
# Builds a fresh Kimai with the shrippen plugins and the Studio Weber demo data.
#
#   demo/kimai/reset.sh [--lang de|en] [--theme default|knust] [--port 8095] [--only Bundle,Bundle] [--down]
#
# Plugins are sibling checkouts of this repo (see PLUGINS below); missing ones are skipped.
# --only limits the plugins (e.g. --only DrehzettelBundle). --down stops and removes everything.
# Login: mara@studio-weber.example.test / demo-password-1 (all demo users share the password).
# DEMO_TODAY is not used here: Kimai runs on the real clock, so the data is placed around today.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"
cd "$HERE"

LANG_=de THEME=default PORT="${KIMAI_PORT:-8095}" ONLY="" DOWN=0
while [ $# -gt 0 ]; do
    case "$1" in
        --lang) LANG_="$2"; shift 2 ;;
        --theme) THEME="$2"; shift 2 ;;
        --port) PORT="$2"; shift 2 ;;
        --only) ONLY="$2"; shift 2 ;;
        --down) DOWN=1; shift ;;
        *) echo "unknown option $1" >&2; exit 2 ;;
    esac
done

# Bundle folder in Kimai -> sibling checkout, install command (empty: none)
PLUGINS=(
    "HolidayBundle|Kimai Holiday Plugin|kimai:bundle:holiday:install"
    "AbrechnungBundle|Kimai Abrechnung|"
    "DrehzettelBundle|Kimai Drehzettel|kimai:bundle:drehzettel:install"
    "MileageBundle|Kimai Anfahrten|kimai:bundle:mileage:install"
    "FarbfaecherBundle|Kimai Farbfächer|"
)

export KIMAI_PORT="$PORT"
COMPOSE=(docker compose -f compose.yaml -f .plugins.yaml)
if [ "$DOWN" = 1 ]; then
    [ -f .plugins.yaml ] || printf 'services: {}\n' > .plugins.yaml
    "${COMPOSE[@]}" down -v
    exit 0
fi

# A clean copy of each plugin: a dev checkout's vendor/, tests/ or node_modules/ would be
# loaded by Kimai as plugin code. Uncommitted changes are included.
stage() {
    mkdir -p .plugins
    rsync -a --delete --exclude .git --exclude vendor --exclude node_modules --exclude tests \
        --exclude var --exclude '*.log' "$1/" ".plugins/$2/"
}

active=()
rm -rf .plugins
{
    echo "# Generated by reset.sh"
    echo "services:"
    echo "  kimai:"
    echo "    volumes:"
    for entry in "${PLUGINS[@]}"; do
        IFS='|' read -r bundle folder _ <<< "$entry"
        if [ -n "$ONLY" ] && [[ ",$ONLY," != *",$bundle,"* ]]; then continue; fi
        if [ ! -f "$ROOT/$folder/$bundle.php" ]; then echo "skip $bundle: $ROOT/$folder not found" >&2; continue; fi
        stage "$ROOT/$folder" "$bundle"
        echo "      - ./.plugins/$bundle:/opt/kimai/var/plugins/$bundle:ro"
        active+=("$entry")
    done
    if [ "$THEME" = knust ]; then
        stage "$ROOT/Kimai Knust" KnustBundle
        echo "      - ./.plugins/KnustBundle:/opt/kimai/var/plugins/KnustBundle:ro"
    fi
} > .plugins.yaml

# www-data, not root: cache files written as root break Apache's worker (500 "not writable")
EXEC=("${COMPOSE[@]}" exec -T --user www-data -e DEMO_LANG="$LANG_" kimai)
CONSOLE=("${EXEC[@]}" /opt/kimai/bin/console)

"${COMPOSE[@]}" down -v --remove-orphans >/dev/null 2>&1 || true
"${COMPOSE[@]}" up -d
echo "waiting for Kimai on 127.0.0.1:$PORT ..."
for i in $(seq 1 60); do
    [ "$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/en/login")" = 200 ] && break
    if [ "$i" = 60 ]; then
        echo "Kimai did not come up; last log lines:" >&2
        "${COMPOSE[@]}" logs --tail 15 kimai | grep -v deprecation >&2
        exit 1
    fi
    sleep 3
done

for entry in "${active[@]}"; do
    IFS='|' read -r _ _ install <<< "$entry"
    [ -n "$install" ] && "${CONSOLE[@]}" "$install" -n
done
[ "$THEME" = knust ] && "${CONSOLE[@]}" kimai:bundle:knust:install -n

"${EXEC[@]}" php /opt/demo/kimai/seed-core.php
for entry in "${active[@]}"; do
    IFS='|' read -r bundle _ _ <<< "$entry"
    seed="/opt/kimai/var/plugins/$bundle/demo/seed.php"
    if "${EXEC[@]}" test -f "$seed"; then
        echo "== $bundle"
        "${EXEC[@]}" php "$seed"
    fi
done
# Reload before the hooks: seeded system settings are read from the cache.
"${CONSOLE[@]}" kimai:reload -n >/dev/null 2>&1
for entry in "${active[@]}"; do
    IFS='|' read -r bundle _ _ <<< "$entry"
    hook="/opt/kimai/var/plugins/$bundle/demo/after-seed.sh"
    if "${EXEC[@]}" test -f "$hook"; then
        "${EXEC[@]}" sh "$hook"
    fi
done
echo "Ready: http://127.0.0.1:$PORT/$LANG_/  mara@studio-weber.example.test / demo-password-1 (theme $THEME)"
