#!/usr/bin/env python3
"""Generates the QML side of Kante from tokens/palette.json.

  qml/Kante/KantePalette.qml   app roles for dark and light ("Leinen"), resolved
                               from the palette (singleton used by KanteStyle)
  tokens/palette.qml           flat brand palette for Plasma widgets (reference)
  qml/Kante/fonts/             the bundled fonts from fonts/ plus OFL.txt

Both .qml files are generated: edit tokens/palette.json and run ./build.sh.
Usage: python3 tools/build-qml.py
"""
import json
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PALETTE = json.loads((REPO / "tokens/palette.json").read_text())
MODULE = REPO / "qml/Kante"
HEADER = "// Generated by tools/build-qml.py from tokens/palette.json. Do not edit."


def theme_tokens(theme):
    """Token name -> hex for one theme ("dark" or "light")."""
    if theme == "dark":
        t = dict(PALETTE["backgrounds"])
        t.update(PALETTE["foregrounds"])
        t.update({name: v["bright"] for name, v in PALETTE["semantic"].items()})
        t["accent-brand"] = PALETTE["accent"]
        return t
    light = PALETTE["light"]
    t = dict(theme_tokens("dark"))
    t.update(light["backgrounds"])
    t.update(light["foregrounds"])
    t.update(light["semantic"])
    t["accent-brand"] = light["accent"]
    return t


def resolve(value, tokens):
    """A role value: token name, "#rrggbb", or [token, alpha] -> QML colour string."""
    alpha = None
    if isinstance(value, list):
        value, alpha = value
    hexv = value if value.startswith("#") else tokens[value]
    hexv = hexv.lower()
    if alpha is None:
        return hexv
    return "#%02x%s" % (round(alpha * 255), hexv[1:])


def camel(name):
    head, *rest = name.split("-")
    return head + "".join(p.capitalize() for p in rest)


def roles_block(theme):
    tokens = theme_tokens(theme)
    lines = []
    for role, value in PALETTE["app"][theme].items():
        lines.append(f'        readonly property color {role}: "{resolve(value, tokens)}"')
    return "\n".join(lines)


def write_palette_module():
    shape = PALETTE["shape"]
    typo = PALETTE["typography"]
    text = f"""{HEADER}
pragma Singleton
import QtQuick

/**
 * Kante palette for apps: the roles KanteStyle reads, for the dark theme
 * and the light theme "Leinen". Surfaces carry alpha (#aarrggbb) so a
 * translucent or blurred platform ground shows through.
 */
QtObject {{
    readonly property string version: "{PALETTE['meta']['version']}"

    readonly property QtObject dark: QtObject {{
{roles_block('dark')}
    }}

    readonly property QtObject light: QtObject {{
{roles_block('light')}
    }}

    // Brand mark fill (icon, badges); not for controls.
    readonly property color brand: "{PALETTE['accent']}"

    // Shape (px at a grid unit of 18; KanteStyle scales them).
    readonly property int chamfer: {shape['chamfer']}
    readonly property int chamferSmall: {shape['chamferSmall']}

    // Type
    readonly property string headingFamily: "{typo['heading']}"
    readonly property real headingLetterSpacing: {typo['headingLetterSpacing']}
    readonly property real labelLetterSpacing: {typo['labelLetterSpacing']}
}}
"""
    (MODULE / "KantePalette.qml").write_text(text)


def write_flat_palette():
    lines = [HEADER, "pragma Singleton", "import QtQuick", "",
             "/*",
             " * Kante — flat palette reference for Plasma widgets and other QML.",
             " * https://github.com/shrippen/shrippen.github.io",
             " *",
             " * Widgets that follow the Plasma theme use Kirigami.Theme.* for all",
             " * interactive colors and these only for brand elements (icon fills,",
             " * priority bands, project hashes, version badges). The opt-in Kante",
             " * style for apps lives in qml/Kante (KanteStyle).",
             " */",
             "QtObject {",
             f'    readonly property color accent: "{PALETTE["accent"]}"', ""]
    for group in ("backgrounds", "foregrounds"):
        for name, value in PALETTE[group].items():
            lines.append(f'    readonly property color {camel(name)}: "{value}"')
        lines.append("")
    for name, v in PALETTE["semantic"].items():
        lines.append(f'    readonly property color {name}: "{v["bright"]}"')
    lines.append("")
    for name, v in PALETTE["semantic"].items():
        lines.append(f'    readonly property color {name}N: "{v["neutral"]}"')
    lines.append("}")
    (REPO / "tokens/palette.qml").write_text("\n".join(lines) + "\n")


def copy_fonts():
    dest = MODULE / "fonts"
    dest.mkdir(parents=True, exist_ok=True)
    for name in PALETTE["typography"]["bundled"] + ["OFL.txt"]:
        shutil.copy2(REPO / "fonts" / name, dest / name)


MODULE.mkdir(parents=True, exist_ok=True)
write_palette_module()
write_flat_palette()
copy_fonts()
print("built qml/Kante/KantePalette.qml, tokens/palette.qml, qml/Kante/fonts/")
